# Generated by Django 5.2.1 on 2025-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_subject_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classregistration',
            name='grade_level',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], default='Grade 1', max_length=10),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='total_subjects',
            field=models.IntegerField(default=0),
        ),
    ]
