# Generated by Django 5.2.1 on 2025-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_subject_allocation', '0002_classregistration_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_role', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
            ],
        ),
    ]
