# Generated by Django 5.2.1 on 2025-05-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_school_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_staff',
            old_name='password',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='school_staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school_staff',
            name='username',
        ),
        migrations.AddField(
            model_name='school_staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
