# Generated by Django 5.2.1 on 2025-06-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_password_school_staff_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.registerschoolstaff')),
            ],
        ),
    ]
