# Generated by Django 5.2.1 on 2025-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics_attendance', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceregistration',
            old_name='user',
            new_name='name',
        ),
    ]
